export const ROOT = "/"

export const PRIVATE_ROUTES = {
        PATH : '/app',
        SUB: {
            LIST_ALL : 'list-all',
            PRODUCT_DETAIL : 'product-detail',
            SIGN_IN : 'sign-in',
            VERIFY: 'verify',
            NOT_FOUND: 'not-found',
            NOT_AUTHENTICATION: 'not-authetication',
            NOT_AUTHORIZATION: 'unauthorized',
            FORGOT_PASSWORD: 'forgot-password',
            RESET_PASSWORD: 'reset-password',
            PROFILE: 'profile',
            EDIT_PROFILE: 'edit-profile',
            CHANGE_PASSWORD: 'change-password',
            DASH_BOARD: 'dashboard',
            CHECK_OUT: 'checkout',
            REGISTER: 'register',
            AUTHORIZATION: 'authorization',
            CAR_LIST : 'car-lists',
            BOOKING : 'booking',
            CAR_DETAIL : 'car-detail',
            CAR_CREATE : 'car-create',
            DRIVER_LIST : 'driver-list',
            BOOKING_LIST : 'booking-list',
            DRIVER_CREATE : 'driver-create',
            ADMIN_REQUEST : 'admin-request',
            ADMIN_DETAIL_REQUEST: 'admin-detail-request',
            TRANSACTION : 'transaction',
            MANAGE_DRIVER_ACCEPT: 'manage-driver-accept',
            MANAGE_ACCOUNT: 'manage-account',
            APPLY_DRIVER: 'apply-driver',
            CHANGE_ROLE_ACCOUNT: 'change-role',
            MANAGER_CAR: 'manager-car',
            REQUEST_IN_EXPIRE : 'request-in-expire',
            BILL_PAYMENT: 'bill-payment',
            DRIVER_BILL: 'driver-bill',
        }
}